name: molebridge
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - comm=0.2.3
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - black==25.1.0
      - certifi==2022.12.7
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==2.1.1
      - chemprojector==0.1.0
      - click==8.2.1
      - contourpy==1.3.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - mypy==1.17.1
      - mypy-extensions==1.1.0
      - networkx==3.3
      - nodeenv==1.9.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pandas==2.3.2
      - pathspec==0.12.1
      - pre-commit==4.3.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pyflakes==3.4.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2025.3.6
      - rich==14.1.0
      - safetensors==0.6.2
      - smmap==5.0.2
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tomli==2.2.1
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - torchvision==0.16.0+cu121
      - tqdm==4.67.1
      - triton==2.1.0
      - types-pyyaml==6.0.12.20250822
      - tzdata==2025.2
      - urllib3==1.26.13
      - virtualenv==20.34.0
      - werkzeug==3.1.3
      - yarl==1.20.1
